---
abstract: 'Per object accessors'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Accessor
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/jib/object-accessor.git
version: 0.48
